version: '3'

services:

    #Webserver
    webserver:
        image: git.bluedragon.nl:5002/docker-images/php-nginx/8.3.4-laravel
        restart: unless-stopped
        environment:
            - UID=1000
            - GID=1000
            - APP_ENV=local
            - APP_DEBUG=true
        volumes:
            - ./:/var/www/html:rw
        networks:
            - backend
            - traefik
        depends_on:
            - database
#            - redis
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.codex.rule=Host(`codex.test`)"
            - "traefik.http.routers.codex.entrypoints=http"
            - "traefik.http.services.codex.loadbalancer.server.port=80"
            - "traefik.docker.network=traefik"

    # MariaDB Database
    database:
        image: mariadb:latest
        restart: unless-stopped
        tty: true
        ports:
            - "1245:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./.docker/data/database:/var/lib/mysql
        networks:
            - backend
            - databases

    #Redis
#    redis:
#        restart: always
#        image: bitnami/redis
#        ports:
#            - "6550:6379"
#        volumes:
#           - ./.docker/data/cache:/bitnami/redis/data
#        networks:
#            - backend
#        environment:
#            - REDIS_PASSWORD=${REDIS_PASSWORD}
#            - REDIS_MASTER_PORT_NUMBER=${REDIS_PORT}

networks:
    backend:
    traefik:
        external: true
    databases:
        external: true
